{% set name = "delaynet" %}
{% set version = "0.3.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/delaynet-{{ version }}.tar.gz
  sha256: 5069b426ac2754972e1066ee3ef587a4bc1b5ac8d4356024dba2e2745cb5b438

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0.1
    - scipy >=1.13.0
    - statsmodels >=0.13.3
    - scikit-learn >=1.5.0
    - numba >=0.59.0
    - infomeasure >=0.6.2
    - python-igraph >=0.11.5
    - synthatdelays >=1.0.2

test:
  imports:
    - delaynet
  commands:
    - pip check
    - pytest tests/
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-codspeed
  source_files:
    - tests

about:
  summary: Delay Propagation in Transportation Networks
  description: |
    Python package to reconstruct and analyse delay functional networks from time series.
    It provides tools for data preparation and detrending, multiple connectivity measures
    (e.g. Granger causality, transfer entropy, correlations), optimal-lag network
    reconstruction, and network analysis.
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://delaynet.readthedocs.io/
  doc_url: https://delaynet.readthedocs.io/
  dev_url: https://github.com/cbueth/delaynet

extra:
  recipe-maintainers:
    - cbueth
    - DrMZanin
